#!/bin/bash

. functions_pub

PackageName=binutils-2.20.1
PackageURL=http://ftp.gnu.org/pub/gnu/binutils/$PackageName.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	mkdir -v ../binutils-build
	cd ../binutils-build
	err_check "[Error] enter $PackageName failed."

	#configure	
	AR=ar AS=as ../$PackageName/configure \
	--prefix=/cross-tools --host=${CLFS_BUILD} --target=${CLFS_TARGET} \
	--with-sysroot=${LFS} --with-lib-path=/tools/lib \
	--disable-nls --enable-shared \
	--enable-64-bit-bfd --disable-multilib
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make configure-host
	err_check "[Error] make $PackageName failed."	

	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	cp -v ../$PackageName/include/libiberty.h /tools/include
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

