#!/bin/bash

. functions_pub

PackageName=gcc-4.5.1
PackageURL=http://ftp.gnu.org/pub/gnu/gcc/$PackageName/$PackageName.tar.bz2
PatchURL=http://patches.cross-lfs.org/dev/gcc-4.5.1-pure64_specs-1.patch


case "${1}" in
download)
	check_and_download $PackageURL
	check_and_download $PatchURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL -static

	#patch
	patch -Np1 -i $LFS_SOURCE/gcc-4.5.1-pure64_specs-1.patch
	err_check "[Error] configure $PackageName failed."

	echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h


	cp -v gcc/Makefile.in{,.orig}
	err_check "[Error] patch $PackageName failed."	

	sed -e "s@\(^CROSS_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g" \
	    gcc/Makefile.in.orig > gcc/Makefile.in
	err_check "[Error] patch $PackageName failed."	

	touch /tools/include/limits.h
	err_check "[Error] patch $PackageName failed."	

	mkdir -v ../gcc-build
	cd ../gcc-build

	#configure	
	AR=ar LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	  ../$PackageName/configure --prefix=/cross-tools \
	--build=${CLFS_BUILD} --host=${CLFS_BUILD} --target=${CLFS_TARGET} \
	--with-sysroot=${LFS} --with-local-prefix=/tools --disable-nls \
	--disable-shared --with-mpfr=/cross-tools --with-gmp=/cross-tools \
	--with-ppl=/cross-tools --with-cloog=/cross-tools \
	--without-headers --with-newlib --disable-decimal-float \
	--disable-libgomp --disable-libmudflap --disable-libssp \
	--disable-threads --enable-languages=c --with-abi=64 
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make all-gcc all-target-libgcc
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install-gcc install-target-libgcc
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL -static
	;;

*)
	exit 1
	;;
esac

#end 

