#!/bin/bash

. functions_pub

PackageName=eglibc-2.12
PackageURL=http://xiangelinux.googlecode.com/files/eglibc-2.12-20100729-r11028.tar.bz2
Package_portsURL=http://xiangelinux.googlecode.com/files/eglibc-ports-2.12-20100729-r11028.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL 
	check_and_download $Package_portsURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	echo "ok, unpress eglibc port.."
	tar xpf $LFS_SOURCE/$(basename $Package_portsURL)
	err_check "[Error] uncompress patch failed."
	
	#Disable linking to libgcc_eh
	cp -v Makeconfig{,.orig}
	sed -e 's/-lgcc_eh//g' Makeconfig.orig > Makeconfig
	err_check "[Error] patch patch failed."

	cp config.make.in{,.orig}
	sed '/ldd-rewrite-script/s:@:${objdir}/&:' config.make.in.orig > config.make.in
	err_check "[Error] patch patch failed."



	mkdir -v ../eglibc-build
	cd ../eglibc-build

	cat > config.cache << "EOF"
libc_cv_forced_unwind=yes
libc_cv_c_cleanup=yes
libc_cv_gnu89_inline=yes
libc_cv_ssp=no
EOF
	err_check "[Error] patch patch failed."

	BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc ${BUILD64}" \
      	AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
	CFLAGS="-O2 -pipe" \
	../eglibc-2.12/configure --prefix=/tools \
        	--host=${CLFS_TARGET} --build=${CLFS_BUILD} \
	        --disable-profile --enable-add-ons \
	        --with-tls --enable-kernel=2.6.0 --with-__thread \
	        --with-binutils=/cross-tools/bin --with-headers=/tools/include \
	        --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

