#!/bin/bash

. functions_pub

PackageName=gcc-4.4.3
PackageURL=http://ftp.gnu.org/gnu/gcc/$PackageName/$PackageName.tar.bz2

GMP_PACKNAME=gmp-4.3.2
GMP_URL=ftp://ftp.gnu.org/gnu/gmp/$GMP_PACKNAME.tar.bz2

MPFR_PACKNAME=mpfr-2.4.2
MPFR_URL=http://www.mpfr.org/$MPFR_PACKNAME/$MPFR_PACKNAME.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	check_and_download $GMP_URL
	check_and_download $MPFR_URL
	;;
build)
	 #step0: unpack.
        unpack_and_enter $PackageName $PackageURL
	
	#unpack GMP.
	tar xf $LFS_SOURCE/`basename $GMP_URL`
	mv {$GMP_PACKNAME,gmp}
	err_check "[Error] unpack gmp failed."
	
	#unpack MPFR
	tar xf $LFS_SOURCE/`basename $MPFR_URL`
	mv {$MPFR_PACKNAME,mpfr}
	err_check "[Error] unpack mpfr failed."


	

        #step1: configure.
        mkdir -p ../build
        err_check "[Error] Binutils: Create build directory failed."

        cd ../build
        err_check "[Error] Binutils: enter build directory failed."
	
	#configure.
        ../$PackageName/configure --prefix=/tools \
		--with-local-prefix=/tools --disable-nls \
		--disable-shared --disable-libssp --enable-languages=c
        err_check "[Error] configure failed."

        #step4: make.
        make
        err_check "[Error] make failed."

        #step5: install
        make install
        err_check "[Error] install failed."


	#adjust.
	ln -vs libgcc.a `gcc -print-libgcc-file-name | sed 's/libgcc/&_eh/'`
        err_check "[Error] gcc: create symbal link failed."
	
	ln -vs gcc /tools/bin/cc
        err_check "[Error] gcc: create symbal link cc failed."

	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

