#!/bin/bash

. functions_pub

PackageName=linux-2.6.32.11
PackageURL=http://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.32.11.tar.bz2

fullname=`basename $PackageURL`


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#make and install.
	make mrproper
	make headers_check
	err_check "[Error] linux_header: check falied."

	make INSTALL_HDR_PATH=dest headers_install
	err_check "[Error] linux_header: make falied."
	
	cp -rv dest/include/* /tools/include
	err_check "[Error] Install linux header files failed."

	#leave.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

