#!/bin/bash

. functions_pub

PackageName=tcl8.5.7
PackageURL=http://downloads.sourceforge.net/sourceforge/tcl/tcl8.5.7-src.tar.gz

fullname=`basename $PackageURL`


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure.
	cd unix
	./configure --prefix=/tools
	err_check "[Error] make $PackageName failed."	


	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName glibc failed."

	#adjust
	chmod -v u+w /tools/lib/libtcl8.5.so	
	err_check "[Error] make libtcl8.5.so writeable failed."

	make install-private-headers
	err_check "[Error] make tcl private header failed."
	
	ln -sv tclsh8.5 /tools/bin/tclsh
	err_check "[Error] $PackageName"

	#leave.
        package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

