#!/bin/bash

. functions_pub

PackageName=gmp-5.0.1
PackageURL=ftp://ftp.gnu.org/gnu/gmp/$PackageName.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	
	#echo "Testing..."
	#echo "CC=$CC"
	#echo "CFLAGS=$CFLAGS_FOR_TARGET"
	#exit 1

	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	

	HOST_CC=gcc CPPFLAGS=-fexceptions CC="${CC} ${BUILD64}" \
	CXX="${CXX} ${BUILD64}" ./configure --prefix=/tools \
		--build=${CLFS_BUILD} --host=${CLFS_TARGET} \
		--enable-cxx
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

