#!/bin/bash

. functions_pub

PackageName=dejagnu-1.4.4
PackageURL=ftp://ftp.gnu.org/gnu/dejagnu/dejagnu-1.4.4.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure
	./configure --prefix=/tools

	#step4: make.
	#step5: install.
	make install
	err_check "[Error] install failed."
	
	#leave.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

