#!/bin/bash

. functions_pub

PackageName=mpfr-2.4.2
PackageURL=http://www.mpfr.org/$PackageName/$PackageName.tar.bz2




case "${1}" in
download)
	#download package from URL.
	check_and_download $PackageURL
	;;
build)

	#step0: unpack.
	unpack_and_enter $PackageName $PackageURL
	patch -Np1 -i ../mpfr-2.4.1-branch_update-2.patch

	#step1: configure.
	./configure --prefix=/tools \
	--build=${CLFS_HOST} --host=${CLFS_TARGET} \
	--enable-shared --with-gmp=/tools
	err_check "configure $PackageName failed."

	#step2: make
	make
	err_check "make $PackageName failed."

	#step3: install
	make install
	err_check "install $PackageName failed."

	#leave.
	package_leave $PackageName $PackageURL
	;;
*)
	exit 1
	;;
esac

#end 

