#!/bin/bash

. functions_pub

PackageName=ppl-0.10.2
PackageURL="http://www.cs.unipr.it/ppl/Download/ftp/releases/0.10.2/ppl-0.10.2.tar.bz2"




case "${1}" in
download)
	#download package from URL.
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
	unpack_and_enter $PackageName $PackageURL

	sed -i "s/__GMP_BITS_PER_MP_LIMB/GMP_LIMB_BITS/g" configure
	err_check "patch $PackageName failed."

	#step1: configure.
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	    --enable-interfaces="c,cxx" --enable-shared \
	    --disable-optimization --with-libgmp-prefix=/tools \
	    --with-libgmpxx-prefix=/tools
	err_check "configure $PackageName failed."

	echo '#define PPL_GMP_SUPPORTS_EXCEPTIONS 1' >> confdefs.h
	err_check "patch $PackageName failed."

	#step2: make
	make
	err_check "make $PackageName failed."

	#step3: install
	make install
	err_check "install $PackageName failed."

	#leave.
	package_leave $PackageName $PackageURL
	;;
*)
	exit 1
	;;
esac

#end 

