#!/bin/bash

. functions_pub

PackageName=cloog-ppl-0.15.9
PackageURL="ftp://gcc.gnu.org/pub/gcc/infrastructure/$PackageName.tar.gz"




case "${1}" in
download)
	#download package from URL.
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
	unpack_and_enter $PackageName $PackageURL

	#step1: configure.

	cp -v configure{,.orig}
	err_check "patch $PackageName failed."

	sed "/LD_LIBRARY_PATH=/d" configure.orig > configure
	err_check "patch $PackageName failed."

	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} --with-bits=gmp \
	    --enable-shared --with-gmp=/tools --with-ppl=/tools

	err_check "configure $PackageName failed."

	#step2: make
	make
	err_check "make $PackageName failed."

	#step3: install
	make install
	err_check "install $PackageName failed."

	#leave.
	package_leave $PackageName $PackageURL
	;;
*)
	exit 1
	;;
esac

#end 

