#!/bin/bash

. functions_pub

PackageName=binutils-2.19.1
PackageURL=http://ftp.gnu.org/gnu/binutils/binutils-2.19.1.tar.bz2

case "${1}" in
download)
	#download package from URL.
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL -pass2

	#step3: configure.
	mkdir -p $LFS_TEMP/build
	cd $LFS_TEMP/build
	err_check "enter directory $LFS_TEMP/build failed"

	../$PackageName/configure --prefix=/tools \
		--disable-nls --with-lib-path=/tools/lib
	err_check "[Error] configure failed."

	#step4: make.
	make
	err_check "[Error] make failed."

	make check
	
	#step5: install
	make install
	err_check "[Error] install failed."


	#step6: adjust tool chain.
	make -C ld clean
	make -C ld LIB_PATH=/usr/lib:/lib
	err_check "[Error]" 

	cp -v ld/ld-new /tools/bin	
	err_check "[Error]" 

	#leave.
        package_leave $PackageName $PackageURL -pass2

	;;
*)
	exit 1
	;;
esac

#end 

