#!/bin/bash

. functions_pub

PackageName=bash-4.0
PackageURL=http://ftp.gnu.org/gnu/bash/bash-4.0.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
  	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure.
	./configure --prefix=/tools --without-bash-malloc \
		ac_cv_func_working_mktime=yes
	err_check "[Error] configure failed."


	#step4: make.
	make
	err_check "[Error] make failed."	

	make tests

	#step5: install.
	make install
	err_check "[Error] install glibc failed."

	#adjust.
	ln -vs bash /tools/bin/sh
	err_check "[Error]"

 	#leave.
        package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

