#!/bin/bash

. functions_pub

PackageName=gcc-4.5.1
PackageURL=http://ftp.gnu.org/pub/gnu/gcc/$PackageName/$PackageName.tar.bz2
PatchURL=http://patches.cross-lfs.org/dev/gcc-4.5.1-pure64_specs-1.patch


case "${1}" in
download)
	check_and_download $PackageURL
	check_and_download $PatchURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL -static

	#patch
	patch -Np1 -i $LFS_SOURCE/gcc-4.5.1-pure64_specs-1.patch
	err_check "[Error] configure $PackageName failed."

	echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h



	cp -v gcc/Makefile.in{,.orig}
	err_check "[Error] patch $PackageName failed."	

	sed -e 's@\(^NATIVE_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g' \
    		gcc/Makefile.in.orig > gcc/Makefile.in
	err_check "[Error] patch $PackageName failed."	


	mkdir -v ../gcc-build
	cd ../gcc-build

	#configure	
	CC="${CC} ${BUILD64}" CXX="${CXX} ${BUILD64}" \
	../gcc-4.5.1/configure --prefix=/tools --disable-multilib \
	--build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	--libexecdir=/tools/lib --with-local-prefix=/tools --enable-long-long \
	--enable-c99 --enable-shared --enable-threads=posix --disable-nls \
	--enable-__cxa_atexit --enable-languages=c,c++ --disable-libstdcxx-pch
	err_check "[Error] configure $PackageName failed."

	#prevent GCC from looking in the wrong 
	#directories for headers and libraries
	cp Makefile{,.orig}
	sed "/^HOST_\(GMP\|PPL\|CLOOG\)\(LIBS\|INC\)/s:-[IL]/\(lib\|include\)::" \
	    Makefile.orig > Makefile
	err_check "[Error] patch $PackageName failed."

	#step4: make.
	make AS_FOR_TARGET="${AS}" \
	    LD_FOR_TARGET="${LD}"
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL -static
	;;

*)
	exit 1
	;;
esac

#end 

