#!/bin/bash

. functions_pub

PackageName=bzip2-1.0.5
PackageURL=http://www.bzip.org/1.0.5/bzip2-1.0.5.tar.gz

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)

	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#step4: make.
	make
	err_check "[Error] make failed."	

	#step5: install.
	make PREFIX=/tools install
	err_check "[Error] install glibc failed."
	
	#leave.
        package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

