#!/bin/bash

. functions_pub

PackageName=bash-4.1
PackageURL=http://ftp.gnu.org/pub/gnu/bash/$PackageName.tar.gz
PatchURL=http://patches.cross-lfs.org/dev/bash-4.1-branch_update-1.patch



case "${1}" in
download)
	check_and_download $PackageURL
	check_and_download $PatchURL
	;;
build)
	#step0: unpack.
	unpack_and_enter $PackageName $PackageURL

	patch -Np1 -i $LFS_SOURCE/bash-4.1-branch_update-1.patch
	err_check "[Error] configure $PackageName failed."

	#configure	
cat > config.cache << "EOF"
ac_cv_func_mmap_fixed_mapped=yes
ac_cv_func_strcoll_works=yes
ac_cv_func_working_mktime=yes
bash_cv_func_sigsetjmp=present
bash_cv_getcwd_malloc=yes
bash_cv_job_control_missing=present
bash_cv_printf_a_format=yes
bash_cv_sys_named_pipes=present
bash_cv_ulimit_maxfds=yes
bash_cv_under_sys_siglist=yes
bash_cv_unusable_rtsigs=no
gt_cv_int_divbyzero_sigfpe=yes
EOF

	CC="${CC} ${BUILD64}" CXX="${CXX} ${BUILD64}" \
    	./configure --prefix=/tools \
    		--build=${CLFS_HOST} --host=${CLFS_TARGET} \
    		--without-bash-malloc --cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	ln -sv bash /tools/bin/sh
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

