#!/bin/bash

. functions_pub

PackageName=bzip2-1.0.5
PackageURL=http://www.bzip.org/1.0.5/bzip2-1.0.5.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	cp -v Makefile{,.orig}
	sed -e 's@^\(all:.*\) test@\1@g' Makefile.orig > Makefile
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}"
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make PREFIX=/tools install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

