#!/bin/bash

. functions_pub

PackageName=diffutils-2.8.7
PackageURL=ftp://alpha.gnu.org/gnu/diffutils/diffutils-2.8.7.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        #unpack_and_enter $PackageName $PackageURL
	tar zxf $LFS_TEMP/$PackageName
        cd $PackageName

	#configure	
	./configure --prefix=/tools \
	--build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

