#!/bin/bash

. functions_pub

PackageName="file-5.04"
PackageURL="ftp://ftp.astron.com/pub/file/$PackageName.tar.gz"




case "${1}" in
download)
	#download package from URL.
	check_and_download $PackageURL
	;;
build)

	#step0: unpack.
	unpack_and_enter $PackageName $PackageURL

	#step1: configure.
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	   --build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "configure $PackageName failed."

	#step2: make
	make
	err_check "make $PackageName failed."

	#step3: install
	make install
	err_check "install $PackageName failed."

	#leave.
	package_leave $PackageName $PackageURL
	;;
*)
	exit 1
	;;
esac

#end 

