#!/bin/bash

. functions_pub

PackageName=flex-2.5.35
PackageURL=http://downloads.sourceforge.net/flex/flex-2.5.35.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL
	patch -Np1 -i $LFS_SOURCE/flex-2.5.35-gcc44-1.patch

	#configure	
	cp -v Makefile.in{,.orig}
	sed "s/-I@includedir@//g" Makefile.in.orig > Makefile.in
cat > config.cache << EOF
ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_realloc_0_nonnull=yes
EOF
	./configure --prefix=/tools \
	--build=${CLFS_HOST} --host=${CLFS_TARGET} \
	--cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

