#!/bin/bash

. functions_pub

PackageName=grep-2.6.3
PackageURL=http://ftp.gnu.org/gnu/grep/$PackageName.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

cat > config.cache << EOF
ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_realloc_0_nonnull=yes
EOF

	#configure	
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
    		--build=${CLFS_HOST} --host=${CLFS_TARGET} \
	        --disable-perl-regexp --without-included-regex \
		--cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

