#!/bin/bash

. functions_pub

PackageName=gzip-1.3.12
PackageURL=http://ftp.gnu.org/gnu/gzip/gzip-1.3.12.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	for file in $(grep -lr futimens *); do
	  cp -v ${file}{,.orig}
	  sed -e "s/futimens/gl_&/" ${file}.orig > ${file}
	done
	./configure --prefix=/tools \
	--build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

