#!/bin/bash

. functions_pub

PackageName=m4-1.4.14
PackageURL=http://ftp.gnu.org/gnu/m4/$PackageName.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
cat > config.cache << EOF
gl_cv_func_btowc_eof=yes
gl_cv_func_mbrtowc_incomplete_state=yes
gl_cv_func_mbrtowc_sanitycheck=yes
gl_cv_func_mbrtowc_null_arg=yes
gl_cv_func_mbrtowc_retval=yes
gl_cv_func_mbrtowc_nul_retval=yes
gl_cv_func_wcrtomb_retval=yes
gl_cv_func_wctob_works=yes
EOF
	cp src/path.c{,.orig}
	sed -e '/"m4.h"/i\#include <sys/stat.h>' \
	    src/path.c.orig > src/path.c
	err_check "[Error] patch $PackageName failed."

	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    	--build=${CLFS_HOST} --host=${CLFS_TARGET} \
        	--cache-file=config.cache
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

