#!/bin/bash

. functions_pub

PackageName=util-linux-ng-2.15.1
PackageURL=http://www.kernel.org/pub/linux/utils/util-linux-ng/v2.15/util-linux-ng-2.15.1.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	./configure --prefix=/tools 
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make BLKID_LIBS="-lblkid -luuid" -C mount mount umount
	err_check "[Error] make $PackageName failed."	
	
	make -C text-utils more
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	cp -v mount/{,u}mount text-utils/more /tools/bin
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

