#!/bin/bash

. functions_pub

PackageName=texinfo-4.13a
PackageURL=http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	./configure --prefix=/tools \
	--build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make -C tools/gnulib/lib
	make -C tools
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

