#!/bin/bash

. functions_pub

PackageName=git-1.6.3.3
PackageURL=http://kernel.org/pub/software/scm/git/git-1.6.3.3.tar.bz2

#depend: zlib

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	./configure --prefix=/tools 
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make 
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install 
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

