#!/bin/bash

#
# Xiange package management system
#

. functions_pub

PackageName=gpkg-0.10.0
PackageURL=http://xiangelinux.googlecode.com/files/gpkg-0.10.0.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL


	#step4: make.
	make 
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make prefix=/tools install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

