#!/bin/bash

. functions_pub

PackageName=util-linux-ng-2.18
PackageURL=http://www.kernel.org/pub/linux/utils/util-linux-ng/v2.18/$PackageName.tar.bz2


case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
	    --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	        --disable-makeinstall-chown
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

