#!/bin/bash

. functions_pub

PackageName=git-1.7.0.6
PackageURL=http://kernel.org/pub/software/scm/git/$PackageName.tar.bz2

#depend: zlib

case "${1}" in
download)
	check_and_download $PackageURL
	;;
build)
	#step0: unpack.
        unpack_and_enter $PackageName $PackageURL

	#configure	
	CC="${CC} ${BUILD64}" ./configure --prefix=/tools \
		ac_cv_c_c99_format=yes\
		ac_cv_fread_reads_directories=no \
		ac_cv_snprintf_returns_bogus=no \
		--build=${CLFS_HOST} --host=${CLFS_TARGET}
	err_check "[Error] configure $PackageName failed."

	#step4: make.
	make 
	err_check "[Error] make $PackageName failed."	

	#step5: install.
	make install 
	err_check "[Error] install $PackageName failed."

	#leave directory.
	package_leave $PackageName $PackageURL
	;;

*)
	exit 1
	;;
esac

#end 

